// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales = 'en' | 'ru'

export type Translation = {
  /**
   * Frontend Template
   */
  title: string
  /**
   * User count: {count}
   * @param {unknown} count
   */
  userCount: RequiredParams1<'count'>
}

export type TranslationFunctions = {
  /**
   * Frontend Template
   */
  title: () => LocalizedString
  /**
   * User count: {count}
   */
  userCount: (arg: { count: unknown }) => LocalizedString
}

export type Formatters = {}

type Param<P extends string> = `{${P}}`

type Params1<P1 extends string> = `${string}${Param<P1>}${string}`

type RequiredParams1<P1 extends string> = Params1<P1>
